version: '3'

services:
  master_mysql:
    image: mysql:5.7
    container_name: master_mysql
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: moma
      MYSQL_DATABASE: test
    networks:
      - mysql_net
    volumes:
      - ./voloum_data/mysql1_data:/var/lib/mysql
      - ./voloum_data/mysql1_conf:/etc/mysql/mysql.conf.d
    expose:
      - '3307'
    ports:
      - "3307:3307"

  slave_mysql:
    image: mysql:5.7
    container_name: slave_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: moma
      MYSQL_DATABASE: test
    networks:
      - mysql_net
    volumes:
      - ./voloum_data/mysql2_data:/var/lib/mysql
      - ./voloum_data/mysql2_conf:/etc/mysql/mysql.conf.d
    expose:
      - '3308'
    ports:
      - "3308:3308"

networks:
  mysql_net: